load("@rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "PartyGameAppleApp",
    srcs = ["PartyGameApp.swift"],
    module_name = "PartyGameAppleApp",
    deps = [
        "//Sources/FirebaseGameService:FirebaseGameService",
        "//Sources/GameCore:GameCore",
        "//Sources/GameIntents:GameIntents",
        "//Sources/GameModules:BoardGameModule",
        "//Sources/GameModules:GameEntryModule",
        "//Sources/GameModules:JoinGameModule",
        "//Sources/GameManagers:GameManagers",
        "//Sources/GameServices:GameServices",
        "//Sources/PartyGameAppCore:PartyGameAppCore",
        "//Sources/SideKickAppCore:SideKickAppCore",
    ],
    visibility = [
        "//Apps/PartyGame/Apple:__pkg__",
        "//Tests/SideKickTests:__pkg__",
    ],
)

swift_library(
    name = "PartyGameAppleAppFirebaseLocal",
    srcs = ["PartyGameApp.swift"],
    module_name = "PartyGameAppleApp",
    tags = ["manual"],
    deps = [
        "//Sources/FirebaseGameService:FirebaseGameServiceSDK",
        "//Sources/GameCore:GameCore",
        "//Sources/GameIntents:GameIntents",
        "//Sources/GameModules:BoardGameModule",
        "//Sources/GameModules:GameEntryModule",
        "//Sources/GameModules:JoinGameModule",
        "//Sources/GameManagers:GameManagers",
        "//Sources/GameServices:GameServices",
        "//Sources/PartyGameAppCore:PartyGameAppCore",
        "//Sources/SideKickAppCore:SideKickAppCore",
    ],
    visibility = [
        "//Apps/PartyGame/Apple:__pkg__",
    ],
)
