load("@rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "FirebaseGameService",
    srcs = [
        "FirebaseGameServiceFactory.swift",
        "FirebaseGameService.swift",
        "FirestoreGameDocumentStore.swift",
    ],
    module_name = "FirebaseGameService",
    deps = [
        "//Sources/FirebaseCoreService:FirebaseCoreService",
        "//Sources/FirestoreDataService:FirestoreDataService",
        "//Sources/GameCore:GameCore",
    ],
    visibility = [
        "//Apps/Jeopardy/Apple:__pkg__",
        "//Sources/JeopardyAppleApp:__pkg__",
        "//Tests/SideKickTests:__pkg__",
    ],
)

swift_library(
    name = "FirebaseGameServiceSDK",
    srcs = [
        "FirebaseGameServiceFactory.swift",
        "FirebaseGameService.swift",
        "FirestoreGameDocumentStore.swift",
    ],
    module_name = "FirebaseGameService",
    tags = ["manual"],
    deps = [
        "//Sources/FirebaseCoreService:FirebaseCoreService",
        "//Sources/FirestoreDataService:FirestoreDataServiceSDK",
        "//Sources/GameCore:GameCore",
        "@swiftpkg_firebase_ios_sdk//:FirebaseAuth",
        "@swiftpkg_firebase_ios_sdk//:FirebaseCore",
        "@swiftpkg_firebase_ios_sdk//:FirebaseFirestore",
    ],
    visibility = [
        "//visibility:public",
    ],
)
